### ISSUE TITLE
brushed points causing problems

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.widgets#128]
This assertion has broken teal.goshawk

![Image](https://user-images.githubusercontent.com/15201933/206460379-b72a14cf-98ea-4568-a315-c1fb610c8bc3.png)

Should we add null.ok to it

**Comment by BLAZEWIM** [comment]
@Polkas  it happened in this commit: https://github.com/insightsengineering/teal.widgets/pull/121/commits/d377fbd7bf41e5ab2baa6b4efdd1dee11239d330 ,
I guess we can remove this assertion, because at least in tm_g_gh_scatterplot it is initialized with empty brush, or is there some reason we should not?

Anyway, question @nikolas-burkoff , while trying to replicate I got different error:
`Assertion on 'brush' failed: Must be of type 'list', not 'NULL'.`
which make sense if you look at the code:

```
clean_brushedPoints <- function(data, brush) { # nolintr
  checkmate::assert_data_frame(data)
  checkmate::assert_list(brush) # my error happened here

  # define original panelvar1 and panelvar2 before getting overwritten
  original_panelvar1 <- brush$mapping$panelvar1
  original_panelvar2 <- brush$mapping$panelvar2

  # Assign NULL to `mapping$panelvar1` and `mapping$panelvar1` if `brush$panelvar1` and `brush$panelvar1` are NULL
  # This will not evaluate the `panelMatch` step in `brushedPoints` and thus will return a non empty dataframe
  if (is.null(brush$panelvar1)) brush$mapping$panelvar1 <- NULL
  if (is.null(brush$panelvar2)) brush$mapping$panelvar2 <- NULL

  bp_df <- brushedPoints(data, brush) # yours was here
```
So I wonder how you managed to get to yours error?

**Comment by Polkas** [comment]
I do not feel comfortable with operations like NULL$aa$bb. Finally the shiny brushedPoints consumes the input so if it accepts NULL then please add @nikolas-burkoff recommendation.
