### ISSUE TITLE
Rewrite documentation of optionalSelectInput

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.widgets#136]
wrong Title and Description:
![image](https://user-images.githubusercontent.com/114988527/209788326-c9e15212-1006-448d-8e5b-d29b65841f8f.png)

**Comment by donyunardi** [comment]
@chlebowa 
Can you help me understand what you meant by wrong title and description?

**Comment by chlebowa** [comment]
The **Title**:
_Hide, Show Label only or display a pickerInput_
and the **Description**:
_[Stable] Hidden input widgets are useful to have the input[[inputId]] variable on available in the server function but no corresponding visual clutter from input widgets that provide only a single choice._ (description)

do not seem to correspond to the function being documented (`optionalSelectInput`).

**Comment by donyunardi** [comment]
I'll look into this. Thank you.

**Comment by donyunardi** [comment]
In the example, should probably mention about using `useShinyjs()`. 

Otherwise, these lines won't work properly:
https://github.com/insightsengineering/teal.widgets/blob/523fd5368b7f2d8a38b2fb6d74c79cc8d09b65b5/R/optionalInput.R#L152

https://github.com/insightsengineering/teal.widgets/blob/523fd5368b7f2d8a38b2fb6d74c79cc8d09b65b5/R/optionalInput.R#L154-L156

**Comment by chlebowa** [comment]
> Also, in the example, we should probably mention about using `useShinyjs()`. Otherwise, these lines won't work properly:

That's probably a good idea. `useShinyjs()` is added somewhere in `teal::init` raw `shiny` but examples most likely need it.
