### ISSUE TITLE
Add tests for `table_with_settings`

### ISSUE THREAD

**Issue by kpagacz** [insightsengineering/teal.widgets#23]
This includes the UI and the behaviour. Possibly will require `shinytest`

**Comment by BLAZEWIM** [comment]
Notes from reseach:

- limitations: while recording tests, some actions get a random ID from shiny, which makes them unrepeatable during tests. because of that app$expect_values() does not work properly, also downloaded file gets the name based on the date an hour,

- system: tests are platform- dependent: snaps performed locally on windows goes to the folder windows-4.2/,

- materials:

https://rstudio.github.io/shinytest2/articles/shinytest2.html

https://rstudio.github.io/shinytest2/articles/use-package.html

https://www.youtube.com/watch?v=EOVPBN5o8F8

https://www.youtube.com/watch?v=7KLv6HdIxvU
